### ISSUE TITLE
Feature request : process and documentation to build a web dapp on top of Nimiq

### ISSUE THREAD

**Issue by glemiere** [nimiq/core-js#384]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-neXwork/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): any
- Browser version(s): any
- Devices/Simulators/Machine affected: any
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: None

## Question or Feature Request
Heeeey!

Nimiq is a great accomplishment, congrats to the team and contributors.
I'd like to know if there is any documentation available to build decentralized web apps (and contracts) on top of the Nimiq Blockchain.

Thank you!
> ...

**Comment by terorie** [comment]
The Nimiq developer describes how contracts work:
https://nimiq-network.github.io/developer-reference/chapters/accounts-and-contracts.html#contracts

The API reference is also useful:
https://doc.esdoc.org/github.com/nimiq-network/core/

Lastly, here is a demo app that shows how to hook the API:
https://demo.nimiq.com/

**Comment by sisou** [comment]
Resources and tutorials for getting started with Nimiq can be found at https://nimiq.com/developers.
