### ISSUE TITLE
MDB_BAD_TXN error

### ISSUE THREAD

**Issue by kochmanski** [nimiq/core-js#387]
![image](https://user-images.githubusercontent.com/20987020/39496026-16e1afd8-4d9d-11e8-8c88-059d9e35adc8.png)

**Comment by Snajper88** [comment]
having a i7-3770k

**Comment by styppo** [comment]
Does this problem still occur in the lastest core version?

**Comment by vikneshvijayakumar** [comment]
Yes

**Comment by paberr** [comment]
Can you confirm that it only happens with Windows 10 after update 1803 using WSL?

**Comment by LTD-Dev** [comment]
I can confirm the same

**Comment by vikneshvijayakumar** [comment]
Yes it is happening of all of my devices on Windows WSL updated with 1803.

**Comment by paberr** [comment]
Apparently, Microsoft has broken cache coherency between read/write and mmap operations in its recent update.

Later today, I will release a temporary workaround that you can use when compiling Nimiq on WSL.

**Comment by paberr** [comment]
Please try using the code published on the branch [paberr/wsl-workaround](https://github.com/nimiq-network/core/tree/paberr/wsl-workaround).
Tell me if further issues exist.

**Comment by LTD-Dev** [comment]
```Node: Nimiq NodeJS Client starting (network=main, dumb, miner=true, rpc=false, metrics=false)
{ Error: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid
    at LMDBBackend._get (/home/iteonix/core/node_modules/@nimiq/jungle-db/dist/lmdb.js:7166:42)
    at LMDBBackend.getSync (/home/iteonix/core/node_modules/@nimiq/jungle-db/dist/lmdb.js:7368:28)
    at LMDBBackend.get (/home/iteonix/core/node_modules/@nimiq/jungle-db/dist/lmdb.js:7392:21)
    at ObjectStore.get (/home/iteonix/core/node_modules/@nimiq/jungle-db/dist/lmdb.js:3716:35)
    at PeerKeyStore.get (/home/iteonix/core/dist/node.js:34689:28)
    at DumbNetworkConfig._init (/home/iteonix/core/dist/node.js:33517:29)
    at DumbNetworkConfig.initPersistent (/home/iteonix/core/dist/node.js:33495:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11) code: -30782 }```

**Comment by sOm2y** [comment]
![capture](https://user-images.githubusercontent.com/2119579/42303870-65007d7c-8077-11e8-88c7-4a92c7f8a924.PNG)
I'm getting mdb corruption error, on master branch core nodejs client under wsl.

**Comment by sOm2y** [comment]
change node_modules/@nimiq/jungle-db/package.json line 4 to ` "main": "dist/leveldb.js", ` 
That will do temp fix

**Comment by vikneshvijayakumar** [comment]
It works!

**Comment by paberr** [comment]
Note that using levelDB instead can only be a temporary workaround, as it might result in "This method does not work reliably using LevelDB" errors when trying to retrieve transactions.

**Comment by hyc** [comment]
For completeness' sake, I did the work to diagnose this bug and notified Microsoft about it https://twitter.com/hyc_symas/status/1013800256088215552

**Comment by terorie** [comment]
Seems like this bug goes deep, its origin is in the Windows kernel: https://github.com/Microsoft/WSL/issues/3451#issuecomment-415251320

It's probably best to disable LMDB on WSL

**Comment by jeffesquivels** [comment]
Closing this stale issue.

For anyone experiencing this in the future, the fix is to update your system to WSL2, see https://github.com/Venemo/node-lmdb/issues/161#issuecomment-1118480146.
