### ISSUE TITLE
Can't use in frontend

### ISSUE THREAD

**Issue by caffeinum** [nimiq/core-js#406]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): Latest from NPM
- Browser version(s): React 16.3
- Devices/Simulators/Machine affected: OS X High Sierra Macbook Pro 2011
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: #399 

## Bug report

Can't `import` nimiq package to use inside React project. Project uses Webpack, Babel. The code is as follows:

```
import nimiq from '@nimiq/core'
```

#### Expected behavior

Imports normally

#### Actual behavior

```
ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in './node_modules/bindings'
```

#### Steps to reproduce

Install nimiq-core into React project
```
npm install --save @nimiq/core
```
Try to import nimiq package
```
import nimiq from '@nimiq/core'
```

#### Crash log? Screenshots? Videos? Sample project?
![image](https://user-images.githubusercontent.com/1909384/40584991-bfffe3f8-61b3-11e8-94d5-5e31499ca168.png)

**Comment by caffeinum** [comment]
I have tried different ways to import, tried to overwrap, but ended up using CDN build, included in the raw html. There is another project, wrapper for nimiq, https://github.com/MatthewDLudwig/NimiqWrapper, but I wanted to make sure there is no way to do this with official build.

**Comment by Albermonte** [comment]
You can't use filesystem (fs) on browser so there's no way to import the core from npm, use the cdn build

**Comment by caffeinum** [comment]
@Albermonte Well, that's considered bad practice in Webpack. Also, you can mock fs in the browser build

**Comment by takahser** [comment]
Had the same problem today with Vue & TypeScript.
A frontend-compatible npm package for the nimiq lib would be nice.

**Comment by sisou** [comment]
For use in browsers, please use the @nimiq/core-web package:
https://www.npmjs.com/package/@nimiq/core-web
