### ISSUE TITLE
backup method

### ISSUE THREAD

**Issue by smithy9901** [nimiq/core-js#447]
Good afternoon, I did not find a way to backup in your documentation.
https://github.com/nimiq-network/core/wiki/JSON-RPC-API#wallet

**Comment by paberr** [comment]
What exactly are you trying to achieve?
If you imported a wallet into the core and want to back it up, take a look at the `wallet` directory in the CWD Nimiq is running.
This is a LMDB directory containing all imported wallets.

Currently, there is no API to export the private key via JSON RPC API.

**Comment by styppo** [comment]
There is no JSON-RPC method to export a key from the Node.js client, but you can use `keytool` (https://github.com/nimiq/core-js/blob/master/clients/nodejs/keytool.js) to import/export keys.

```
Usage:
    node keytool.js <command> [options]
Commands:
    list                List addresses managed in this client. Default is tagged with asterisk
    set-default         Set the client default address. Use together with --address
    import              Import new addresses to this client
    export              Export private key from this client
Options:
    --address ADDRESS   Address to export. Defaults to the client default.
    --format FORMAT     Format of key for import or export
                        Possible values: words (default), hex, base64
    --type TYPE         Type of key for import.
                        Possible values: auto (default), legacy
    --help              Display this help page
```
