### ISSUE TITLE
Use Nimiq Core in browser without CDN

### ISSUE THREAD

**Issue by takahser** [nimiq/core-js#448]
## New issue checklist

- [ x ] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [ x ] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): CDN
- Browser version(s): not relevant
- Devices/Simulators/Machine affected: typescript

## Bug report

I'd like to use the Nimiq library in the browser. Since the npm package relies on node and therefore cannot be used in the browser, I started off with using the [cdn](https://cdn.nimiq.com/nimiq.js), by including the url into the html index file of my vue app.
While it works, this solution is not sufficient, for a variety of reasons.

My next logical step was to save the cdn file locally and import it into my typescript files.

#### Expected behavior

Cdn can be saved locally and imported in a typescript powered web app.

#### Actual behavior

The typescript compiler throws an error, when running the nimiq code:

```
Module parse failed: Identifier '_interopRequireDefault' has already been declared (2361:9)
You may need an appropriate loader to handle this file type.
|     _createClass3 = _interopRequireDefault(_createClass2);
|
> function _interopRequireDefault(e) {
|   return e && e.__esModule ? e : {
|     default: e

 @ ./src/main.ts 6:0-36 14:12-17
 @ multi (webpack)-dev-server/client?http://192.168.0.17:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

#### Steps to reproduce

- clone the reproduction repo
- run `yarn install && yarn serve`

#### Crash log? Screenshots? Videos? Sample project?

Reproduction repo is available [here](https://github.com/takahser/nimiq-vue-experiments)

**Comment by takahser** [comment]
I did some troubleshooting, here are my results:


- If either of the two declaration of the `_interopRequireDefault` function **that are not anonymous** are removed (i.e. [L2268][0] or [L2377][1]), the code will execute. This resolves the original "Identifier '_interopRequireDefault' has already been declared" error.
- TypeScript offers [various ways][2] to import a module.
  - single export from a module: `import { Bar } from "./Foo";`
  - importing default exports: `import bar from "./foo" // imports foo's default export and makes it locally available as 'bar'`
  - entire module as single variable: `import * as foo from "./foo";`
- I tried all possible imports for Nimiq, results:

| import type                      | code                             | `Nimiq` value                                                   | works                        |
|----------------------------------|----------------------------------|-----------------------------------------------------------------|------------------------------|
| single export from a module      | `import { Nimiq } from './nimiq'`  | `undefined`                                                       | No                           |
| importing default exports | `import Nimiq from './nimiq'` | `undefined`                                                       | No                           |
| entire module as single variable        | `import * as Nimiq from './nimiq'`      | `Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}` | Yes, but how to use `Nimiq`? |

- Conclusion: although it's possible to import the `Nimiq` module, it still doesn't seem usable. 


[0]: https://github.com/takahser/nimiq-vue-experiments/blob/master/src/nimiq.js#L2268
[1]: https://github.com/takahser/nimiq-vue-experiments/blob/master/src/nimiq.js#L2377
[2]: https://www.typescriptlang.org/docs/handbook/modules.html#import-a-module-for-side-effects-only

**Comment by sisou** [comment]
For Typescript support, we have a spacial types package here: https://www.npmjs.com/package/@nimiq/core-types

@jeffesquivels is working on packaging a browser build of the core as well, so you can include or bundle it from your node_modules.

**Comment by jsappme** [comment]
trying to use the following in a vue app:

```"@nimiq/core-web": "^1.4.1",```

importing it like this:

 ```import Nimiq from '@nimiq/core-web';```

here are the types of error i am getting:

``` Uncaught TypeError: _nimiq_core_web__WEBPACK_IMPORTED_MODULE_5___default.a.load is not a function at Module.eval ```

**Comment by Bettelstab** [comment]
@jsappme Could you provide a sample repository?

**Comment by AndrewBogushevich** [comment]
Hi, wasn't able to import @nimiq/core-web properly into vue&ts project.
`import * as Nimiq from '@nimiq/core-web';`
getting error
`Cannot find module '@nimiq/core-web'`

Here is [sample repository](https://bitbucket.org/Andrei_Bahushevich/nimiq_vue_ts), importing nimiq in Home.vue file

**Comment by sisou** [comment]
We merged the PR that adds an ES6 module build yesterday: https://github.com/nimiq-network/core/pull/463
It is not released as a package yet.
Additionally, types are going to be merged soon, too: https://github.com/nimiq-network/core/pull/466

**Comment by sisou** [comment]
This is the package with an ES6 module for browsers:
https://www.npmjs.com/package/@nimiq/core-web
