### ISSUE TITLE
Uncaught exception with light node when connecting to seed nodes

### ISSUE THREAD

**Issue by rraallvv** [nimiq/core-js#454]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
  @nimiq/core  v1.4.1
- Browser version(s):
  Chrome 71.0.3578.80 (Official Build) (64-bit)
- Devices/Simulators/Machine affected:
  Macbook Air Mid-2012 running macOS High Sierra 10.13.6 (17G3025)
- Reproducible in the testnet? (Yes/No):
  I haven't tried the testnet yet
- Related issues:
  None that I know of

#### Expected behavior

> See below

#### Actual behavior

> The node seems to be working as expected, except for the uncaught exception shown in the crash log

#### Steps to reproduce

> Install Nimiq Core v1.4.1, change the file `clients/nodejs/index.js` so that it allows starting a light node

```
// if (config.type === 'light') {
//     console.error('Light node type is temporarily disabled');
//     process.exit(1);
// }
```

> Then start the node in light mode and wait for it to connect to the seed nodes. The exception seems to be thrown once every 20 or 40 times I start a node, but this of course is my subjective appreciation.

#### Crash log? Screenshots? Videos? Sample project?

```
[I 14:10:10] Node: Connected to wss://seed-17.nimiq.com:8443/f1240638c6dd670467f22a04b58f7740
Uncaught exception: Cannot read property 'inv' of null
Uncaught exception: Cannot read property 'inv' of null TypeError: Cannot read property 'inv' of null
    at LightConsensusAgent._sendFreeWaitingInvVectors (/rbd/pnpm-volume/27b38bed-10e1-4739-94a6-1e2d349ca835/node_modules/.registry.npmjs.org/@nimiq/core/1.4.1/node_modules/@nimiq/core/dist/node.js:19189:45)
    at Timeout.BaseConsensusAgent._timers.setInterval [as _onTimeout] (/rbd/pnpm-volume/27b38bed-10e1-4739-94a6-1e2d349ca835/node_modules/.registry.npmjs.org/@nimiq/core/1.4.1/node_modules/@nimiq/core/dist/node.js:19057:63)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[I 14:10:12] Node: Connected to wss://seed-11.nimiq.network:8443/0a7ac560e381f65f72f6628ac8005627
```

**Comment by jeffesquivels** [comment]
Closing stalled issue.

I don't think we will work on this since light nodes are not officially supported and all efforts are now geared towards albatross.
