### ISSUE TITLE
BasePoolMiner ignore config using ws

### ISSUE THREAD

**Issue by Azard** [nimiq/core-js#459]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): latest
- Reproducible in the testnet? (Yes/No):  Yes

#### Expected behavior

connect to `ws://poolServer:port`

#### Actual behavior

failed

#### Crash log? Screenshots? Videos? Sample project?

https://github.com/nimiq-network/core/blob/master/src/main/generic/miner/BasePoolMiner.js#L64

this line ignore config file protocol, force using `wss`

**Comment by terorie** [comment]
The config file assumes that the pool is running `wss` and has no option to switch to `ws`.
You can only set the `host` and `port`, of the pool, not the protocol.
```js
    poolMining: {
        enabled: false,
        host: null,
        port: -1,
        mode: 'smart',
        deviceData: null
    },
```

**Comment by terorie** [comment]
@Azard I added a config parameter to enable mining on `ws://` pools.
Run `git clone https://github.com/terorie/nimiq-core -b custom-pool-protocol` to get my patched source code with support for `ws://` pools.

Then, in your config, set something like this:
```js
    // Configure pool mining on this node.
    poolMining: {
        enabled: "yes",
        protocol: "ws",
        //host: "pool.domain",
        //port: 8444,
    },
```

**Comment by Azard** [comment]
@terorie Thanks, I change it too, but I hope this patch could merge into Nimiq core

**Comment by jeffesquivels** [comment]
Closing stalled issue.

Since all efforts are now geared toward albatross, it's unlikely this would be implemented.
