### ISSUE TITLE
NanoPoolMiner not getting correct head

### ISSUE THREAD

**Issue by Albermonte** [nimiq/core-js#465]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.4.1
- Browser version(s): 1.14.1
- Devices/Simulators/Machine affected: Browsers
- Reproducible in the testnet? (Yes/No): Yes

## Bug report

Nano Miner won't start mining until disconnect and reconnect to a pool. The head received by the pool isn't correct.

#### Expected behavior

> Start mining on the first connection.

#### Actual behavior

> Nothing

#### Steps to reproduce

> Start a NanoPoolMiner work and try to mine connecting to a pool.

#### Crash log? Screenshots? Videos? Sample project?

> NanoPoolMiner: q9iMogTF4Kx1fDMEA0eHFX8KyRtgPid7iyBXW9OVshE= (from pool) is unknown and not a successor of the head

**Comment by jeffesquivels** [comment]
Closing this issue as it seems to be already fixed.
