### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by terorie** [nimiq/core-js#470]
https://www.torproject.org/

Is Nimiq ready to be used as an [onion service](https://www.torproject.org/docs/onion-services.html.en) on Tor, yet? What needs to be done to connect to Nimiq peers on Tor?

### Considerations

According to my research, this is the current situation:

 * __Onion Dumb node ➡️ Clearnet__
    * ❌ _On a simple Tor installation_, nodes make no attempt to communicate over Tor (they don't know how to).
    * ✅ _On a proper installation with a Tor inet gateway_, nodes can easily reach public peers without revealing their address (Tails/Whonix)
    * ✏️ I suggest adding support for a SOCKS proxy, which makes it possible to route all outgoing connections through Tor.
 * __Onion Passive node ⬅️ Tor__
   * ✅ Nodes can accept incoming connections and provide services if the Tor daemon is properly configured. They see that all connections are coming from `localhost`.
   * ⚠️ Afaik, the node binds on 0.0.0.0 by default, leaving the port exposed to Clearnet.
 * __General issues__
   * ⚠️ Nimiq's peer discovery (`GetAddr/Addr`) will lead to addresses of Tor nodes being sent to clearnet peers. `.onion` addresses aren't reachable outside of the Tor network making the clearnet nodes send out pointless DNS queries.
   * ⚠️ Peer discovery messages will include either the IP address of exit nodes or `localhost` instead of `NetAddress.UNSPECIFIED`, when describing onion services. ([PeerAddress](https://github.com/nimiq-network/core/blob/cde980f87d0f73154097e462a2e160cb01cc516e/src/main/generic/network/address/PeerAddress.js#L246), [NetAddress](https://github.com/nimiq-network/core/blob/master/src/main/generic/network/address/NetAddress.js))
 * __WebRTC connections__: No idea, but imho it'd be best to disable WebRTC support for Tor connections.

### Setup

With proper caution, Nimiq nodes can probably be setup as onion services without any changes to the source. The setup would roughly look like this:

 * Get the Tor service running
 * Setup a virtual network with a gateway that routs all traffic through Tor (e.g. Tails or Whonix)
 * Setup `HiddenServiceDir` and `HiddenServicePort`
 * Set the node to `WS` mode
 * Set the hostname as specified in `HiddenServiceDir`
 * Disable WebRTC signaling and communication
 * Configure firewall to only incoming traffic to `HiddenServicePort` from `localhost`
 * Let the node listen at `HiddenServicePort`

##### SOCKS proxy

A command line flag/configuration option to route all communication through a [SOCKS5](https://en.wikipedia.org/wiki/SOCKS) proxy. This is the standard way of outgoing communication through Tor.

##### Explicit signaling of Tor support

A new `ONION` [Protocol](https://github.com/nimiq-network/core/blob/master/src/main/generic/network/Protocol.js) and `PeerAddress` variant could be introduced to describe hidden services.
 * ⚠️ This is not a backwards-compatible change, so communication with older peers is impossible.
 * ✅ The peer discovery mechanism of clearnet nodes won't get disturbed

**Comment by mar-v-in** [comment]
Regarding socks proxy support: did you check if the current client works well with tools like [socksify](https://linux.die.net/man/1/socksify)?
