### ISSUE TITLE
Arguments of 'equals' methods should always be typed any

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/core-js#485]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

**Comment by jeffesquivels** [comment]
Closing stale issue.
