### ISSUE TITLE
Copy paste recovery words

### ISSUE THREAD

**Issue by Serasar** [nimiq/core-js#487]
I understand that manually writing and entering recovery words is supposed to improve security, but logging in into Safe account becomes tedious if your browser cookies is deleted. It would be convenient to be able to copy paste all words during recovery phase.

**Comment by danimoh** [comment]
Hello Serasar.

We'll soon release a new version of the Nimiq Keyguard with improved usability.
The new Keyguard will support import and export of new Login Files which are a convenient way of logging in into your account.
