### ISSUE TITLE
Pico mempool does not fire transaction-* events

### ISSUE THREAD

**Issue by sisou** [nimiq/core-js#500]
I'm trying out the pico consensus branch, and after subscribing to an address, it does not fire `transaction-added` or `transaction-mined` events.

The Nano consensus/mempool does.

**Comment by alilooki** [comment]
Like

**Comment by styppo** [comment]
The `Client` API now exposes these events through `addTransactionListener`: https://github.com/nimiq/core-js/blob/master/src/main/generic/api/Client.js#L884.

**Comment by alilooki** [comment]
Hi
