### ISSUE TITLE
DeviceData is not sent to a mining pool when in Smart mode

### ISSUE THREAD

**Issue by tomkha** [nimiq/core-js#517]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [ ] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues: #401 

#### Expected behavior

> Device data is sent to a mining pool

#### Actual behavior

> Extra data is sent instead

#### Steps to reproduce

> Run miner in smart mode

deviceData is not passed to the BasePoolMiner class

https://github.com/nimiq/core-js/blob/3498bf5e9dfcbaae5fdfb543a98c4bf76a8c2785/src/main/generic/miner/SmartPoolMiner.js#L16

**Comment by jeffesquivels** [comment]
Closing this issue as it seems to be already fixed.
