### ISSUE TITLE
RPC method getTransactionReceipt always returns transactionIndex: -1

### ISSUE THREAD

**Issue by tomkha** [nimiq/core-js#528]
## New issue checklist

- [*] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [*] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): core-js 1.5.4
- Browser version(s): N/A
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): Yes
- Related issues:

#### Expected behavior

> return a valid transaction index in the block.

#### Actual behavior

> -1 is always returned

#### Steps to reproduce

```
jq -n '{jsonrpc: "2.0", id: 1, method: "getTransactionReceipt", params: ["a9129575cff8d38aa703b9aa9f1ca1c9420ef2101447db2172026929478ba44f"]}' \
| curl -s -H "Content-Type: application/json" -d @- 'http://localhost:8648/' \
| jq -r '.'
{
  "jsonrpc": "2.0",
  "result": {
    "transactionHash": "a9129575cff8d38aa703b9aa9f1ca1c9420ef2101447db2172026929478ba44f",
    "transactionIndex": -1,
    "blockNumber": 100105,
    "blockHash": "477befaf0e32b22eb25dacc3ac7b3e5d6581101b0ab354948910d8b4c5ed491b",
    "confirmations": 766578,
    "timestamp": 1529726417
  },
  "id": 1
}
```

The reason is that [here](https://github.com/nimiq/core-js/blob/ffadff31af9f9ca05bb163cf90e5ce9cc34979c2/clients/nodejs/modules/JsonRpcServer.js#L327) the transaction hash is compared with its hexadecimal presentation:
```
tx.hash().equals(hash)
```
while it should be something like
```
tx.hash().toHex() === hash
or
tx.hash().equals(Nimiq.Hash.fromHex(hash))
```

**Comment by jeffesquivels** [comment]
Thanks for the bug report, @tomkha! I looked into it and you're right about the problem and about the solution.

If you would like to send a Pull Request to fix it, I would be happy to review it and merge it :-).
