### ISSUE TITLE
RPC method getRawTransactionInfo always returns inMempool: false

### ISSUE THREAD

**Issue by tomkha** [nimiq/core-js#529]
This doesn't work as liveTx.confirmations is undefined if a transaction is pending in mempool

https://github.com/nimiq/core-js/blob/21fd0730b0acc4ec74bb305ca0dced247a47d3f6/clients/nodejs/modules/JsonRpcServer.js#L281

**Comment by styppo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/nimiq/core-js/issues/529](https://trello.com/c/XpwhNtMI/38-https-githubcom-nimiq-core-js-issues-529)
