### ISSUE TITLE
minning by php script.

### ISSUE THREAD

**Issue by asedali** [nimiq/core-js#534]
how can I write a PHP script to mine nimiq?

**Comment by tomkha** [comment]
You'll need a Nimiq node installed somewhere, call its getWork/getBlockTemplate RPC methods to construct the block header. Use Argon2d hashing function with certain parameters to hash the block header. Vary the last 4 bytes of the header until you find a hash matching PoW criterion. Then call submitBlock RPC to push a newly mined block to the network.

**Comment by terorie** [comment]
@asedali Did this answer your question? If so, please close.
