### ISSUE TITLE
Client transaction history returns knownTxs above the limit

### ISSUE THREAD

**Issue by sisou** [nimiq/core-js#546]
When using the `limit` parameter of the Core Clients `getTransactionsByAddress()` method, the Client returns any passed-in `knownDetails`, that are above the limit parameter. E.g. when I set the limit to `100`, but pass in 112 known details, I get an array of 12 transactions back from the method (112-100=12). In my case, all known details are already `confirmed`.

I think this is due to the check in the method, that checks any `MINED` and `CONFIRMED` transactions of the known details, which are _not_ included in the receipts, again.

However, they are not included in the receipts, because the receipts have been cut off at the `limit` earlier.

**Comment by sisou** [comment]
Not only are the extra known details returned, they are also checked again against the blockchain, meaning for each extra known detail the respective block and transaction is fetched from the network. This is especially unnecessary for `CONFIRMED` details.

@mar-v-in Do you think we can remove the check of CONFIRMED transaction details in
https://github.com/nimiq/core-js/blob/2b7e8edd8f1ce61481c4ce28f677766e4cba5a33/src/main/generic/api/Client.js#L782-L784

**Comment by mar-v-in** [comment]
@sisou the confirmed transactions should only be reverified if they are included in a block after `sinceBlockHeight`. `sinceBlockHeight` is the last block height you consider fully verified and don't expect changes since, so this is intended.

What is the value of `sinceBlockHeight` you are working with? Is there maybe some bug in handling it?

**Comment by sisou** [comment]
No, we are not using that in the wallet. It's always set to 0. But if that's the way to go, then we'll start using it.
