### ISSUE TITLE
Different number of confirmations returned by getTransactionByHash and getTransactionReceipt

### ISSUE THREAD

**Issue by tomkha** [nimiq/core-js#585]
when a transaction is just included in the block it's counted as 1 confirmation, isn't it?

compare this
https://github.com/nimiq/core-js/blob/db39adc5d5a0176225746d690ec9f224bbe268b5/clients/nodejs/modules/JsonRpcServer.js#L359

with this
https://github.com/nimiq/core-js/blob/db39adc5d5a0176225746d690ec9f224bbe268b5/clients/nodejs/modules/JsonRpcServer.js#L772

**Comment by sisou** [comment]
Yes you are right. Mined in a block means 1 confirmation. So the `getTransactionReceipt` is off by one. Do you want to open a PR for it?

**Comment by tomkha** [comment]
BTW, what about block confirmations?
https://github.com/nimiq/core-js/blob/db39adc5d5a0176225746d690ec9f224bbe268b5/clients/nodejs/modules/JsonRpcServer.js#L746

**Comment by tomkha** [comment]
Added https://github.com/nimiq/core-js/pull/586

**Comment by sisou** [comment]
Yes, you can add block confirmation fix to your PR also.

**Comment by jeffesquivels** [comment]
This issue seems to be fixed by the merging of #586 , so I'm closing it. Feel free to reopen it if there's something still missing.
