### ISSUE TITLE
github repo missing tag `v1.5.8`

### ISSUE THREAD

**Issue by josefschabasser** [nimiq/core-js#604]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [X] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information
This repository is missing tag `v1.5.8` and a corresponding release. The current DEB package is v1.5.8 but I can't find the commit to rebuild on my own.

**Comment by jeffesquivels** [comment]
Thanks for the report, @josefschabasser!

 I have tagged the commit from where `v1.5.8` was taken and created the corresponding release.
