### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by magmel48** [nimiq/core-js#617]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.5.8
- Browser version(s): not applicable
- Devices/Simulators/Machine affected: Mac OS Monterey 12.1 with M1 chip
- Reproducible in the testnet? (Yes/No): not applicable
- Related issues: not applicable

#### Expected behavior

Can be installed as npm dependency without node-gyp build errors.

#### Actual behavior

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nimiq_node_native/src/native/argon2.o
clang: error: the clang compiler does not support '-march=native'
make: *** [Release/obj.target/nimiq_node_native/src/native/argon2.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

-march=native definitely is not right option for clang on M1 environments. Specified here:
- https://github.com/nimiq/core-js/blob/master/binding.gyp#L41
- https://github.com/nimiq/core-js/blob/master/binding.gyp#L45

**Comment by magmel48** [comment]
@sisou

**Comment by sisou** [comment]
I saw it, but I'm not maintainer of this package. Especially not the native builds. I'll let the person know.

**Comment by magmel48** [comment]
is there any update?

**Comment by jeffesquivels** [comment]
Hi @magmel48, sorry for the delay with this, most of our efforts are currently on 2.0, and not so much on adding new features/supporting new platforms on 1.0.

I hope to have some time to look at this next week, hopefully it won't be too complicated it to get it working (*famous last words* 😅).

**Comment by Eligioo** [comment]
@magmel48 have you tried with Node 15.14 as stated in the README? I haven't used the artifacts yet but I managed to compile the native part on an M1.

**Comment by Eligioo** [comment]
BaseConsensus: Synced with all connected peers (2), consensus established. So it's possible to compile for M1 @jeffesquivels

**Comment by magmel48** [comment]
hi @Eligioo 

I would prefer to stay on Node 16 since it's LTS version. Anyway, I created my own fork for own purposes where I removed such instructions like -march=native and now it works OK

**Comment by magmel48** [comment]
btw, in some packages with similar problem I found an interesting solution - optional flag with M1 detection. So, it would make sense if you integrate something like that

**Comment by 10wpressure** [comment]
@magmel48 hi, can you kindly share your fork (make it public maybe)?
Or alternatively - can maybe recreate your changes in [my fork](https://github.com/10wpressure/nimiq-core-js)?
I tried deleting all 3 mentions of -march=native but it did not help sadly...

**Comment by magmel48** [comment]
@10wpressure I also removed the entire "xcode_settings" (in binding.gyp) section since there is no option specified except only one -march=native.

**Comment by jeffesquivels** [comment]
Hi guys! Sorry again for the delay, I did take a look at this issue back in April, but didn't had easy access to an M1 Mac to test possible bugfix. I just came back to it and AWS now supports M1-based EC2 instances which made it possible to debug and test everything.

AFAIC, the fix in https://github.com/nimiq/core-js/tree/jeff/fix_build_apple_m1 should fix the compilation issue (while maintaining the compiler optimizations, both on x86 and M1 macs), can you please test it and let me know?

**Comment by magmel48** [comment]
hi @jeffesquivels 

I have tested the fix - works on M1 now!

**Comment by jeffesquivels** [comment]
Perfect! Thanks @magmel48
