### ISSUE TITLE
Building on node js 18 / Ubuntu 22.04 gives an error

### ISSUE THREAD

**Issue by brantje** [nimiq/core-js#626]
### General information

- Library version(s): Node 18 (Building with 16 works, didn't try with 17)
- Browser version(s): N/A 
- Devices/Simulators/Machine affected: Ubuntu 22.04
- Reproducible in the testnet? (Yes/No):  N/A
- Related issues:

#### Expected behavior
I've tried building on node 18, however this gave me an error

#### Actual behavior
Bulding with node 18 gives the following error: https://pastebin.com/FsS7p7Jc

#### Steps to reproduce
Using nvm i installed node 18, ran an `npm install` and the error follows

#### Crash log? Screenshots? Videos? Sample project?
https://pastebin.com/FsS7p7Jc

**Comment by cb5890** [comment]
Hi Sander,

I already fixed that this morning - checkout this branch.

See https://github.com/nimiq/core-js/tree/curd/nodejs18

There building should work 😊👍

Best,
Curd

**Comment by jeffesquivels** [comment]
Thanks to @cb5890, this should already be fixed on `master` now.
