### ISSUE TITLE
Unable to build core-js using Node v22.1.0

### ISSUE THREAD

**Issue by joeleol** [nimiq/core-js#647]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): v1.6.2

## Bug report

While building core-js with Node v22.1.0 the process is terminated due to various errors. 

I reverted to Node v20.13.1 and could build again, so I guess the issue came in a version between these two.

#### Expected behavior

core-js to be built successfully.

#### Actual behavior

Process is terminated due to various errors. 

#### Steps to reproduce

Follow the Quickstart guide on a machine with Node v22.1.0 installed.

#### Crash log? Screenshots? Videos? Sample project?

Please see attached log.

**Comment by joeleol** [comment]
The log...
[core-js error.pdf](https://github.com/nimiq/core-js/files/15320535/core-js.error.pdf)

**Comment by sisou** [comment]
From your log I see that `node-lmdb` fails to build with Node 22's `gyp`. I don't see any mention of Node 22 in any of their issues, PRs or recent commits.

Seems like @jeffesquivels can have a look again, he already added support for Node 20 to `node-lmdb`.

**Comment by jeffesquivels** [comment]
Hi @joeleol,

Can you please try again using the latest commit on `master` and let me know if it works for you?

Thanks,

**Comment by joeleol** [comment]
Hi @jeffesquivels 

Compiles now with Node v22 - thanks!

**Comment by jeffesquivels** [comment]
@joeleol Nice. You're welcome!
